services:
  backend:
    restart: unless-stopped
    build:
      context: ./decibelio_backend
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=desarrollo
      - DB_PASSWORD=desarrollo
      - DB_NAME=database_decibelio
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - backend_data:/usr/src/app/storage

  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: database_decibelio
      MYSQL_USER: desarrollo
      MYSQL_PASSWORD: desarrollo
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: decimetrix-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  backend_data: